name: CI/CD

on:
  push:
    branches: [main] # Correction : utiliser la branche main au lieu de master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # Correction : utiliser "name" pour nommer l'étape
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16 # Correction : utiliser la version 16 de Node.js

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/

      - name: Install dependencies
        run: npm install

      - name: Publish package to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
